<?php

// System

define("YGGDRASIL_VERSION", "0.7.0");


// General

if(!defined("YGGDRASIL_ENVIRONMENT")) {
	define("YGGDRASIL_ENVIRONMENT", "prod");
}


// Frontend

if(!defined("YGGDRASIL_FRONTEND_ROOT_DIR")) {
	define("YGGDRASIL_FRONTEND_ROOT_DIR", realpath("../www"));
	// THROW ERROR IF UNDEFINED
}

if(!defined("YGGDRASIL_FRONTEND_ROOT_URL")) {
	define("YGGDRASIL_FRONTEND_ROOT_URL", "//{$_SERVER["SERVER_NAME"]}/");
	// THROW ERROR IF UNDEFINED
}

if(!defined("YGGDRASIL_FRONTEND_MEDIA_URL")) {
	define("YGGDRASIL_FRONTEND_MEDIA_URL", YGGDRASIL_FRONTEND_ROOT_URL); // TODO
}

if(!defined("YGGDRASIL_FRONTEND_URL_TYPE")) {
	define("YGGDRASIL_FRONTEND_URL_TYPE", "folder"); // TODO
}


// Backend files and directories

if(!defined("YGGDRASIL_BACKEND_ROOT_DIR")) {
	define("YGGDRASIL_BACKEND_ROOT_DIR", realpath("./") . DS);
}

if(!defined("YGGDRASIL_BACKEND_ROOT_URL")) {
	define("YGGDRASIL_BACKEND_ROOT_URL", "//{$_SERVER["SERVER_NAME"]}" . dirname($_SERVER["SCRIPT_NAME"]) . "/");
}

if(!defined("YGGDRASIL_BACKEND_CORE_DIR")) {
	define("YGGDRASIL_BACKEND_CORE_DIR", YGGDRASIL_BACKEND_ROOT_DIR . "_core" . DS);
}

if(!defined("YGGDRASIL_BACKEND_TEMP_DIR")) {
	define("YGGDRASIL_BACKEND_TEMP_DIR", YGGDRASIL_BACKEND_ROOT_DIR . "_temp" . DS);
}

if(!defined("YGGDRASIL_BACKEND_TEMP_COMPILER_DIR")) {
	define("YGGDRASIL_BACKEND_TEMP_COMPILER_DIR", YGGDRASIL_BACKEND_TEMP_DIR . "compiler" . DS);
}

if(!defined("YGGDRASIL_BACKEND_TEMP_PUBLISHER_DIR")) {
	define("YGGDRASIL_BACKEND_TEMP_PUBLISHER_DIR", YGGDRASIL_BACKEND_TEMP_DIR . "publisher" . DS);
}

if(!defined("YGGDRASIL_BACKEND_TEMP_PUBLISHER_LOCKFILE")) {
	define("YGGDRASIL_BACKEND_TEMP_PUBLISHER_LOCKFILE", YGGDRASIL_BACKEND_TEMP_DIR . "publisher-lock.json");
}

if(!defined("YGGDRASIL_BACKEND_PAGE_DIR")) {
	define("YGGDRASIL_BACKEND_PAGE_DIR", YGGDRASIL_BACKEND_ROOT_DIR . "_pages" . DS);
}

if(!defined("YGGDRASIL_BACKEND_CONFIG_DIR")) {
	define("YGGDRASIL_BACKEND_CONFIG_DIR", YGGDRASIL_BACKEND_ROOT_DIR . "_config" . DS);
}

if(!defined("YGGDRASIL_BACKEND_CONFIG_GLOBALS_FILE")) {
	define("YGGDRASIL_BACKEND_CONFIG_GLOBALS_FILE", YGGDRASIL_BACKEND_CONFIG_DIR . "globals.php");
}

if(!defined("YGGDRASIL_BACKEND_PAGE_CONTENT_FILE")) {
	define("YGGDRASIL_BACKEND_PAGE_CONTENT_FILE", "content.php");
}

if(!defined("YGGDRASIL_BACKEND_PAGE_SETTINGS_FILE")) {
	define("YGGDRASIL_BACKEND_PAGE_SETTINGS_FILE", "page.php");
}

if(!defined("YGGDRASIL_BACKEND_TEMPLATE_DIR")) {
	define("YGGDRASIL_BACKEND_TEMPLATE_DIR", YGGDRASIL_BACKEND_ROOT_DIR . "_templates" . DS);
}

if(!defined("YGGDRASIL_BACKEND_SNIPPET_DIR")) {
	define("YGGDRASIL_BACKEND_SNIPPET_DIR", YGGDRASIL_BACKEND_ROOT_DIR . "_snippets" . DS);
}

// Backend misc

if(!defined("YGGDRASIL_BACKEND_DATETIME_FORMAT")) {
	define("YGGDRASIL_BACKEND_DATETIME_FORMAT", "d.m.Y H:i");
}

if(!defined("YGGDRASIL_BACKEND_ACTION_TIMEOUT")) {
	define("YGGDRASIL_BACKEND_ACTION_TIMEOUT", 1200);
}

if(!defined("YGGDRASIL_BACKEND_MENU_POSITION")) {
	define("YGGDRASIL_BACKEND_MENU_POSITION", "right"); // TODO
}

// Parser

if(!defined("YGGDRASIL_BACKEND_TAG_NAMESPACE")) {
	define("YGGDRASIL_BACKEND_TAG_NAMESPACE", "yggdrasil-namespace");
}

if(!defined("YGGDRASIL_BACKEND_TAG_SECTION")) {
	define("YGGDRASIL_BACKEND_TAG_SECTION", "section");
}

if(!defined("YGGDRASIL_BACKEND_TAG_SECTION_RENDER")) {
	define("YGGDRASIL_BACKEND_TAG_SECTION_RENDER", "renderSection");
}

if(!defined("YGGDRASIL_BACKEND_TAG_SNIPPET")) {
	define("YGGDRASIL_BACKEND_TAG_SNIPPET", "snippet");
}

if(!defined("YGGDRASIL_BACKEND_TAG_PHPCODE")) {
	define("YGGDRASIL_BACKEND_TAG_PHPCODE", "php");
}

if(!defined("YGGDRASIL_BACKEND_TAG_MINIFY_JS")) {
	define("YGGDRASIL_BACKEND_TAG_MINIFY_JS", "minifyjs");
}

if(!defined("YGGDRASIL_BACKEND_TAG_MINIFY_CSS")) {
	define("YGGDRASIL_BACKEND_TAG_MINIFY_CSS", "minifycss");
}


?>